Repository VFPC/VFPC, pull requests merged in 2021-08, with the labels that each got.

#61 Nav Perf Check
  analyzeFP.cpp
  analyzeFP.hpp
Labels: bug

#56 SRD Parser
  Constant.hpp
  README.md
  analyzeFP.cpp
  analyzeFP.hpp
Labels: enhancement, api

#60 Dismiss Checks
  Constant.hpp
  analyzeFP.cpp
  analyzeFP.hpp
Labels: enhancement

#55 Odd-Even Rule
  README.md
  analyzeFP.cpp
Labels: bug

#64 Data Output Tidying Up
  analyzeFP.cpp
  analyzeFP.hpp
Labels: bug

#66 Route Output
  analyzeFP.cpp
  analyzeFP.hpp
Labels: enhancement

#69 Clock Fixes
  src/analyzeFP.cpp
  src/analyzeFP.hpp
Labels: bug

#71 Backup Try-Catches
  src/analyzeFP.cpp
  src/analyzeFP.hpp
Labels: admin

#72 Mills is messing with the API
  src/analyzeFP.cpp
Labels: bug

#73 This isn't up to date...
  src/analyzeFP.cpp
Labels: admin

#74 Min/Max Output Change
  src/analyzeFP.cpp
  src/analyzeFP.hpp
Labels: enhancement

#77 Auto-clear cache on release
  cacheclear.yml
Labels: admin

#84 API Refresh Time
  src/Constant.hpp
  src/analyzeFP.hpp
Labels: bug
